A2:shell sb virus history test

history:history.c
	gcc -o history history.c -lncurses

shell:shell.c
	gcc -o shell shell.c

sb:sb.c
	gcc -o sb sb.c -lm

virus:virus.c
	gcc -o virus virus.c

test:test.c
	gcc -o test test.c -lncurses

clean:
	rm -f shell sb virus gpt test history